runtime: nodejs14

service: memory

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 100
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

instance_class: F1

env_variables:
  REDISHOST: '10.60.12.68'
  REDISPORT: '6379'

vpc_access_connector:
  name: "projects/big-for-costumer-dev/locations/us-central1/connectors/bfc-serveless-connector"